### ISSUE TITLE
wandb agent doesn't run my program file using conda env 

### ISSUE THREAD

**Issue by sandipan1** [elyall/wandb_on_slurm#1]
Hi
Thanks for making this wonderful piece of code. I am trying to wandb sweep run in hpc. 
I have initialized conda env in the slurm script .However when the wandb agent starts it starts with a different python executable 

`2020-11-30 02:46:31,639 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python train.py ....`

Any comments on how to solve this ?

**Comment by elyall** [comment]
I did not have this issue, as well my understanding is `/usr/bin/env` points to the first python on your `$PATH` and `conda activate` appends the environment you specify to the front of your path. If that's not the proper python executable then add `conda activate ENVIRONMENT_NAME` to the `start-agent.sh` script before `wandb agent` is called. The conda installation (and environment) does need to be on the shared volume accessible to all workers. 

If you still have issues, adding `echo $PATH; which python` to the .sbatch script and to the start-agent.sh script would help in debugging.

**Comment by sandipan1** [comment]
`conda activate env_name` in `start-agent.sh` did not work for me. I think something wrong is happening with the srun command with subprocess. If I run `wandb.agent(sweepid)` , it works fine. I'll probably try to debug it later.

**Comment by elyall** [comment]
I assume when you successfully run `wandb.agent(sweepid)` you mean within your main script and not a subprocess, correct? That's fine if you want your job to run on only one node, and is actually the proper approach in that case, but it will not parallelize the job over multiple nodes. I will clarify this point in the readme. 

I would add the following code to both the `.sbatch` script and `start-agent.sh` script to help debug:
```
echo $PATH
which python
which conda
conda info --envs
```

**Comment by sandipan1** [comment]
Thanks for this. Your code is working perfectly fine. My issue was with another environment variable.(`MKL_THREADING_LAYER`) which was causing the subprocess to fail. Now its fixed
