### ISSUE TITLE
Array job - option to supply sweep id

### ISSUE THREAD

**Issue by PatBall1** [elyall/wandb_on_slurm#2]
Really cool repo, thanks. I think it'd be good to have an option to supply an already generated sweepID. This would allow extending an existing sweep and allow a sweep to take place as an array job rather than just across nodes.

**Comment by elyall** [comment]
This was a trivial enhancement and does allow for multiple agents on single nodes. However it does add the complexity that you have to ensure the code is consistent, especially if the sweep is generated on a different machine. Though in that case Ray Tune with its dependency pickling might be preferred. 670e65689be8344e8e71cb9aa221b80fd607bb6d
