### ISSUE TITLE
How to sweep using the gpus available within a given node?

### ISSUE THREAD

**Issue by TomerGalanti** [elyall/wandb_on_slurm#3]
Suppose I have two nodes with 5 gpus per node. How can I run 10 sweeps over the full set of gpus, instead of two sweeps with <=5 gpus each allocated to the sweep?

Thanks!!

**Comment by elyall** [comment]
That is outside the scope of this repo or my knowledge. A [post](https://wandb.ai/site/articles/multi-gpu-sweeps) turned up from a quick google search makes it seem like you should try changing `start-agent.sh` to be:

```shell
#!/bin/bash
CUDA_VISIBLE_DEVICES=0 wandb agent $1 --project $2
CUDA_VISIBLE_DEVICES=1 wandb agent $1 --project $2
CUDA_VISIBLE_DEVICES=2 wandb agent $1 --project $2
CUDA_VISIBLE_DEVICES=3 wandb agent $1 --project $2
CUDA_VISIBLE_DEVICES=4 wandb agent $1 --project $2
```
