### ISSUE TITLE
Compute nodes with no network access

### ISSUE THREAD

**Issue by jacanchaplais** [elyall/wandb_on_slurm#4]
I appreciate you making this content public!

I stumbled here because the compute nodes on my HPC cluster are not networked, so I can't use sweeps naively. I have skimmed the README and source code, and it isn't clear to me if this issue is addressed by your method. Does your workflow rely on networked compute nodes?

**Comment by elyall** [comment]
W&B's Sweeps is a cloud service that requires networking, however they do offer a [local controller](https://docs.wandb.ai/guides/sweeps/advanced-sweeps/local-controller) meant for debugging that you could use to run everything locally. Nothing about this repo requires networking so you could plug and play the local controller into it.
