### ISSUE TITLE
slurmstepd: error: execve(): start-agent.sh: Permission denied

### ISSUE THREAD

**Issue by Karl-Chung** [elyall/wandb_on_slurm#5]
Hello. Thanks to your code sharing.
I got some problem implement this.
When I run this code,
`running script
slurmstepd: error: execve(): start-agent.sh: Permission denied
srun: error: my-node01: task 0: Exited with exit code 13`
I tried to change start-agent.sh to abstract path. But didn't work.
How can I fix it?

Best,
Karl

**Comment by elyall** [comment]
Hi, I've not seen this before. Some things that come to mind:
- ensure `start-agent.sh` is executable  (`chmod +x start-agent.sh`)
- it might be a bug in your actual training code (I'm not familiar with [exit code 13](https://hpc-discourse.usc.edu/t/exit-codes-and-their-meanings/414)) in which case you should ensure your training code works on the cluster alone by running it in an interactive job without W&B.
- it could be an issue with your slurm implementation: it's possible a new version of slurm breaks this repo but I think that's highly unlikely, or different nodes were/are running different versions of slurm (for instance if you ran the code during a cluster update). Reporting your slurm version (`sinfo -V`) would be helpful in this case (as well as ensuring it's consistent across nodes, but that's probably unlikely as well).

**Comment by Karl-Chung** [comment]
Thanks to reply,
I solve the problem! It seems related to permission when using subprocess.Popen.
To allow the permission, adding 'shell=True' solve the error.
`sp.append(subprocess.Popen(['srun',
                        '--nodes=2',
                        '--ntasks=10',
                        '-w',
                        node,
                        'start-agent.sh',
                        sweep_id,
                        project_name], shell=True))`.
